- hosts: newt_docker_hosts
  become: true
  become_user: root

  tasks:
    - name: Run docker compose up pull always for newt stack ({{ ansible_ssh_user }} user)
      ansible.builtin.shell:
        cmd: docker compose up -d --build --pull always
      args:
        chdir: /home/{{ ansible_ssh_user }}/docker_apps/newt
      become: true

